server:
  port: 9011
spring:
  application:
    name: user-service
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    platform: h2

# cloud config
eureka:
  client:
    serviceUrl:
      defaultZone: http://biezhi:biezhi.pwd@localhost:9800/eureka/

# logging config
logging:
  level:
    root: INFO
    org.org.hibernate: TRACE
