spring:
  application:
    name: api-gateway-zuul
server:
  port: 9050
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://biezhi:biezhi.pwd@localhost:9800/eureka/